import { Link } from "react-router-dom";
import Layout from "../components/Layout";
import {
  FaChartLine,
  FaCheckCircle,
  FaFolderOpen,
  FaLightbulb,
  FaBriefcase,
  FaTools,
} from "react-icons/fa";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { FaDownload } from "react-icons/fa";

function Analysis() {
  const analysis = JSON.parse(localStorage.getItem("analysis"));
  const downloadPDF = () => {

  const doc = new jsPDF();

// Background Header
doc.setFillColor(6, 182, 212);
doc.rect(0, 0, 210, 35, "F");

// Title
doc.setTextColor(255, 255, 255);
doc.setFont("helvetica", "bold");
doc.setFontSize(22);
doc.text("AI Resume Analyzer", 20, 22);

// Reset color
doc.setTextColor(0, 0, 0);

// Date
const today = new Date().toLocaleDateString();

doc.setFontSize(11);
doc.text(`Generated: ${today}`, 20, 45);

// ATS Score
doc.setFontSize(18);
doc.setFont("helvetica", "bold");
doc.text(`ATS Score: ${analysis.ats_score}%`, 20, 58);

// Grade
const grade =
  analysis.ats_score >= 90 ? "A+" :
  analysis.ats_score >= 80 ? "A" :
  analysis.ats_score >= 70 ? "B" :
  analysis.ats_score >= 60 ? "C" :
  "Needs Improvement";

doc.setTextColor(0, 150, 0);
doc.text(`Grade: ${grade}`, 20, 70);

doc.setTextColor(0, 0, 0);

  autoTable(doc, {
    startY: 45,
    head: [["Skills Found"]],
    body:
      analysis.skills_found?.map(skill => [skill]) || [],
  });

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 10,
    head: [["Sections Found"]],
    body:
      analysis.sections_found?.map(section => [section]) || [],
  });

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 10,
    head: [["AI Suggestions"]],
    body:
      analysis.suggestions?.map(item => [item]) || [],
  });

  doc.text(
    `Experience : ${analysis.experience?.level || "Fresher"}`,
    20,
    doc.lastAutoTable.finalY + 20
  );

  doc.setTextColor(120);

  doc.text(
    "Generated by AI Resume Analyzer",
    20,
    doc.lastAutoTable.finalY + 35
  );

  doc.save("ATS_Report.pdf");

};

  if (!analysis) {
    return (
      <Layout>
        <div className="text-center py-24">
          <h1 className="text-4xl font-bold mb-6">
            No Analysis Found
          </h1>

          <Link
            to="/upload"
            className="bg-cyan-500 hover:bg-cyan-600 px-8 py-3 rounded-xl"
          >
            Upload Resume
          </Link>
        </div>
      </Layout>
    );
  }

  const score = analysis.ats_score || 0;

  return (
    <Layout>
      <div className="max-w-7xl mx-auto px-8 py-12">

        <h1 className="text-5xl font-bold mb-10">
          Resume Analysis
        </h1>

        <div className="grid lg:grid-cols-3 gap-8">

          {/* ATS CARD */}

          <div className="bg-slate-900 rounded-3xl border border-slate-800 p-8 flex flex-col items-center">

            <h2 className="text-slate-400 text-xl mb-8">
              ATS SCORE
            </h2>

            <div className="relative w-56 h-56">

              <svg
                className="w-full h-full -rotate-90"
              >

                <circle
                  cx="112"
                  cy="112"
                  r="90"
                  stroke="#1e293b"
                  strokeWidth="14"
                  fill="none"
                />

                <circle
                  cx="112"
                  cy="112"
                  r="90"
                  stroke="#06b6d4"
                  strokeWidth="14"
                  fill="none"
                  strokeLinecap="round"
                  strokeDasharray="565"
                  strokeDashoffset={
                    565 - (565 * score) / 100
                  }
                />

              </svg>

              <div className="absolute inset-0 flex flex-col justify-center items-center">

                <h2 className="text-6xl font-bold text-cyan-400">
                  {score}%
                </h2>

                <p className="text-slate-400">
                  ATS Match
                </p>

              </div>

            </div>

          </div>

          {/* SCORE CARDS */}

          <div className="lg:col-span-2 grid md:grid-cols-2 gap-6">

            <div className="bg-slate-900 rounded-2xl border border-slate-800 p-6">

              <div className="flex items-center gap-3 mb-4">

                <FaChartLine className="text-cyan-400 text-2xl"/>

                <h2 className="text-xl font-bold">
                  Contact
                </h2>

              </div>

              <div className="bg-slate-800 rounded-full h-3">

                <div
                  className="bg-cyan-400 h-3 rounded-full"
                  style={{
                    width:
                      analysis.breakdown.contact * 2 + "%"
                  }}
                />

              </div>

              <p className="text-3xl font-bold mt-4">
                {analysis.breakdown.contact}
              </p>

            </div>

            <div className="bg-slate-900 rounded-2xl border border-slate-800 p-6">

              <div className="flex items-center gap-3 mb-4">

                <FaFolderOpen className="text-blue-400 text-2xl"/>

                <h2 className="text-xl font-bold">
                  Sections
                </h2>

              </div>

              <div className="bg-slate-800 rounded-full h-3">

                <div
                  className="bg-blue-500 h-3 rounded-full"
                  style={{
                    width:
                      analysis.breakdown.sections * 2 + "%"
                  }}
                />

              </div>

              <p className="text-3xl font-bold mt-4">
                {analysis.breakdown.sections}
              </p>

            </div>
                        <div className="bg-slate-900 rounded-2xl border border-slate-800 p-6">

              <div className="flex items-center gap-3 mb-4">

                <FaTools className="text-green-400 text-2xl" />

                <h2 className="text-xl font-bold">
                  Skills
                </h2>

              </div>

              <div className="bg-slate-800 rounded-full h-3">

                <div
                  className="bg-green-500 h-3 rounded-full"
                  style={{
                    width:
                      analysis.breakdown.skills * 3 + "%"
                  }}
                />

              </div>

              <p className="text-3xl font-bold mt-4">
                {analysis.breakdown.skills}
              </p>

            </div>

            <div className="bg-slate-900 rounded-2xl border border-slate-800 p-6">

              <div className="flex items-center gap-3 mb-4">

                <FaBriefcase className="text-yellow-400 text-2xl" />

                <h2 className="text-xl font-bold">
                  Experience
                </h2>

              </div>

              <p className="text-4xl font-bold text-yellow-400">
                {analysis.experience?.level || "Fresher"}
              </p>

              <p className="text-slate-400 mt-2">
                Resume Experience Level
              </p>

            </div>

          </div>

        </div>

        {/* Skills + Sections */}

        <div className="grid md:grid-cols-2 gap-8 mt-10">

          <div className="bg-slate-900 rounded-2xl border border-slate-800 p-8">

            <h2 className="text-2xl font-bold mb-6 flex items-center gap-3">

              <FaCheckCircle className="text-green-400"/>

              Skills Found

            </h2>

            <div className="flex flex-wrap gap-3">

              {analysis.skills_found?.map((skill) => (

                <span
                  key={skill}
                  className="bg-green-500/20 border border-green-500 text-green-400 px-4 py-2 rounded-full"
                >
                  {skill}
                </span>

              ))}

            </div>

          </div>

          <div className="bg-slate-900 rounded-2xl border border-slate-800 p-8">

            <h2 className="text-2xl font-bold mb-6 flex items-center gap-3">

              <FaFolderOpen className="text-blue-400"/>

              Sections Found

            </h2>

            <div className="flex flex-wrap gap-3">

              {analysis.sections_found?.map((section) => (

                <span
                  key={section}
                  className="bg-blue-500/20 border border-blue-500 text-blue-400 px-4 py-2 rounded-full"
                >
                  {section}
                </span>

              ))}

            </div>

          </div>

        </div>
       <div className="flex justify-end mb-8">

  <button
    onClick={downloadPDF}
    className="flex items-center gap-2 bg-cyan-500 hover:bg-cyan-600 px-6 py-3 rounded-xl font-semibold transition"
  >
    <FaDownload />
    Download ATS Report
  </button>

</div>
                {/* AI Suggestions */}

        <div className="mt-10 bg-slate-900 rounded-2xl border border-slate-800 p-8">

          <h2 className="text-2xl font-bold mb-8 flex items-center gap-3">

            <FaLightbulb className="text-yellow-400" />

            AI Suggestions

          </h2>

          <div className="grid md:grid-cols-2 gap-5">

            {analysis.suggestions?.length > 0 ? (

              analysis.suggestions.map((item, index) => (

                <div
                  key={index}
                  className="bg-slate-800 rounded-xl p-5 border border-slate-700 hover:border-cyan-500 transition"
                >

                  <div className="flex items-start gap-3">

                    <FaLightbulb className="text-yellow-400 mt-1 text-xl" />

                    <p className="text-slate-300">
                      {item}
                    </p>

                  </div>

                </div>

              ))

            ) : (

              <div className="col-span-2 bg-green-500/20 border border-green-500 rounded-xl p-6">

                <div className="flex items-center gap-3">

                  <FaCheckCircle className="text-green-400 text-2xl" />

                  <p className="text-green-300 text-lg font-semibold">
                    Excellent! No major improvements required.
                  </p>

                </div>

              </div>

            )}

          </div>

        </div>

      </div>

    </Layout>

  );

}

export default Analysis;